name: 'CI'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: numso/slack-stream/slack-stream/create@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          steps: 'Test|Build|Deploy'
          blah: ${{ steps }}

      - uses: numso/slack-stream/slack-stream/start@master
      - run: sleep 3s
      - uses: numso/slack-stream/slack-stream/finish@master

      - uses: numso/slack-stream/slack-stream/start@master
      - run: sleep 1s
      - uses: numso/slack-stream/slack-stream/finish@master

      - uses: numso/slack-stream/slack-stream/start@master
      - run: sleep 2s
      - uses: numso/slack-stream/slack-stream/finish@master

      - if: ${{ failure() }}
        uses: numso/slack-stream/slack-stream/error@master
