name: 'CI'
on:
  push:
    branches:
      - master
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: numso/slack-stream/create@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          steps: 'Test|Build|Deploy'
      - run: sleep 1s
      - uses: numso/slack-stream/update@master
        with:
          name: 'Test'
      - run: sleep 3s
      - uses: numso/slack-stream/update@master
        with:
          name: 'Build'
      - run: sleep 3s
      - uses: numso/slack-stream/update@master
        with:
          name: 'Deploy'
