name: Test
on: pull_request
env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: numso/slack-stream/slack-stream/create@master
        with:
          steps: 'Test'

      - run: aws --version
      - run: echo $PATH
      - run: env

      - uses: numso/slack-stream/slack-stream/start@master
      - run: sleep 1s
      - uses: numso/slack-stream/slack-stream/finish@master

      - if: ${{ failure() }}
        uses: numso/slack-stream/slack-stream/error@master
      - if: ${{ cancelled() }}
        uses: numso/slack-stream/slack-stream/cancel@master
